services:
  backend:
    image: podfeeds
    ports:
      - 8080:8080
    volumes:
      - ./podcasts.yaml:/etc/podfeeds/podcasts.yaml
  reverse_proxy:
    image: nginx
    ports:
      - 8081:8081
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

