#!/usr/bin/env bash

# Based on this tutorial:
# https://junegunn.github.io/fzf/tips/ripgrep-integration/

PODFEED_JSON=$(mktemp)
export PODFEED_JSON

_podfeed_query "$1" | fzf \
	--disabled \
	--ansi \
	--bind "change:reload:_podfeed_query {q}" \
	--bind "enter:become:cat $PODFEED_JSON | jq -r '.results[0] | (\"- \" + .feedUrl + \" # \" + .collectionName)'" \
	--select-1 \
	--exit-0

rm -rf "$PODFEED_JSON"
