#!/usr/bin/env bash

# Based on this tutorial:
# https://junegunn.github.io/fzf/tips/ripgrep-integration/

PODFEED_JSON=$(mktemp)
export PODFEED_JSON

# I couldn't get the start: binding to work.
# Fedora 44. FZF 0.70.0.

_podfeed_query "$1" | fzf \
	--disabled \
	--ansi \
	--select-1 \
	--bind "change:reload:_podfeed_query {q}" \
	--bind "enter:become:cat $PODFEED_JSON | jq -r '.results[0] | (\"- \" + .feedUrl + \" # \" + .collectionName)'"

rm -rf "$PODFEED_JSON"
